install: |-
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo apt-get install bsdmainutils
  sudo gem install --no-rdoc --no-ri pdd
  cd src/bundle
  bundle install
  cd ../..
architect:
- froy001
assets:

merge:
  fast-forward: only
  rebase: true
  script: |-
    rspec spec
    echo "Merging!!"
  commanders:
  - froy001
deploy:
  script: |-
    bundle
  commanders:
  - froy001
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  pre: false
  script:
  commanders:
  - froy001
